# -*- coding: utf-8 -*-
"""sea_level_predictor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z1hUdZb9Jf0MW9gOdSy8sPXRC2rlmS0C
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import linregress

# %matplotlib inline

# Loading sea level data from a direct link
url = "https://raw.githubusercontent.com/freeCodeCamp/boilerplate-sea-level-predictor/main/epa-sea-level.csv"
df = pd.read_csv(url)

# Display first rows to verify data
df.head()

def draw_plot():
    # Create scatter plot
    fig, ax = plt.subplots(figsize=(10, 6))
    ax.scatter(df['Year'], df['CSIRO Adjusted Sea Level'])

    # First line of best fit (all data)
    res_all = linregress(df['Year'], df['CSIRO Adjusted Sea Level'])
    years_all = pd.Series(range(1880, 2051))
    sea_level_all = res_all.intercept + res_all.slope * years_all
    ax.plot(years_all, sea_level_all, 'r')

    # Second line of best fit (from year 2000)
    df_recent = df[df['Year'] >= 2000]
    res_recent = linregress(df_recent['Year'], df_recent['CSIRO Adjusted Sea Level'])
    years_recent = pd.Series(range(2000, 2051))
    sea_level_recent = res_recent.intercept + res_recent.slope * years_recent
    ax.plot(years_recent, sea_level_recent, 'g')

    # Labels and title
    ax.set_xlabel('Year')
    ax.set_ylabel('Sea Level (inches)')
    ax.set_title('Rise in Sea Level')

    # Save figure
    fig.savefig('sea_level_plot.png')

    return fig

draw_plot()